# Control file for continuous integration testing at http://travis-ci.org/

language: cpp
compiler: gcc
sudo: required
dist: trusty
#before_install:
#install:
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install cmake; fi
script:
  - cmake -H. -Bbuild && cmake --build build -- -j 4 && echo Testing && bin/dsgvg test
